### ISSUE TITLE
Upgrade reactor-core to 3.2.x

### ISSUE THREAD

**Issue by JamesGallicchio** [reactor/reactor-scala-extensions#26]
Reactor 3.2.0 (Californium) was released nearly 9 months ago. The 3.2.x series is more stable with a variety of improvements and bug fixes.

The outdated dependency conflicts with another library my project uses, so upgrading would be very appreciated. However, I'm not a Reactor power user, so my knowledge is pretty limited and I'm not sure how painful this upgrade would be.

Is there a reason for the delay? Let me know if there's anything I can do to help you upgrade to 3.2 :-)

**Comment by sinwe** [comment]
@JamesGallicchio Thanks for your comment.

There are 2 main reasons that the upgrade gets delayed:

1. I’m in the middle of major refactoring that have breaking backward compatibility. I’m trying to make it backward compatible.
2. My project has completed using the earlier version and doesn’t have major changes required. Hence my activity on this is a little bit lower than usual.

However if you need to upgrade to 3.2, I can look into it in the next couple of days. Alternatively, feel free to raise PR and I can take a look and help on releasing it.

**Comment by sinwe** [comment]
@JamesGallicchio It turns out that upgrade to 3.2.x is already on the way in the new version. It's a major version upgrade with some of old classes being deprecated.
You can start trying version 0.4.0

**Comment by JamesGallicchio** [comment]
I'd be happy to help with upgrading.
