### ISSUE TITLE
Target Scala release 2.13

### ISSUE THREAD

**Issue by JamesGallicchio** [reactor/reactor-scala-extensions#27]
Currently the code is being cross-built and published for 2.13.0-M3, but 2.13.0 has been released. Could that be updated?

Thanks in advance! :-)

**Comment by sinwe** [comment]
@JamesGallicchio, Yes eventually 2.13 will be cross-built. It depends on whether all the libraries used to build/test/release are available for 2.13.

Thanks for raising issue though.

**Comment by sinwe** [comment]
Compilation seems to be working already. The only problem is with gradle scaladoc plugin that break with scaladoc 2.13 as indicated https://github.com/gradle/gradle/issues/9855

**Comment by sinwe** [comment]
Without being able to generate the scaladoc, it won't be able to be released to the public.

**Comment by sullis** [comment]
starting point:  Scala 2.13.1
https://github.com/reactor/reactor-scala-extensions/pull/39

**Comment by sinwe** [comment]
This is now done as part of #44. Thank you @giabao
