### ISSUE TITLE
Publishing Scala 2.12 maven artifact?

### ISSUE THREAD

**Issue by florind** [reactor/reactor-scala-extensions#3]
Unfortunately I could only find a 0.2.5-SNAPSHOT published in sonatype.org for Scala 2.12 but no stable version in Maven central.
Is there any reason for not publishing a Scala 2.12 based lib?

Thanks!
florin

**Comment by sinwe** [comment]
@florind The main reason was that I couldn't make the cross build stable enough within time-boxed. That's why it was available on snapshot only.

**Comment by sinwe** [comment]
@florind This is available in 0.3.1 version now
