### ISSUE TITLE
Convert to/from Mono/JMono

### ISSUE THREAD

**Issue by florind** [reactor/reactor-scala-extensions#4]
This is more a confusion I have: I am using Webflux and I need to convert from reactor.core.publisher.Flux/Mono and the reactor.core.scala.publisher.Flux/Mono counterpart.
I couldn't find an "scala.publisher.Flux.asJava" or "reactor.core.scala.publisher.Flux.asScala" straight converter, similar to those found in JavaConverters or OptionConverters so I'd like to know if there is a way to perform such conversion using the current API.

**Comment by sinwe** [comment]
@florind There is already .asJava for converting scala to java. However, I agree that there isn't one for converting java to scala.
In 0.3.1-SNAPSHOT, I've opened up the apply method in Flux/Mono companion object, so you'll be able to use Flux(reactor.core.publisher.Flux) and Mono(reactor.core.publisher.Mono)

**Comment by sinwe** [comment]
@florind version 0.3.1 is released and you can convert between java and scala Mono/Flux

**Comment by Satya758** [comment]
Hi @sinwe 
**Flux.apply** is public but **Mono.apply** is still private
https://github.com/reactor/reactor-scala-extensions/blob/master/src/main/scala/reactor/core/scala/publisher/Mono.scala#L1836

In this following commit, I see changes to Flux but not to Mono
https://github.com/reactor/reactor-scala-extensions/commit/faad6f9914abcf59872ab19627780eec5b96a4db

Thanks
Satya

**Comment by sinwe** [comment]
Thanks @Satya758, I'm currently on long holiday. If need it urgently, feel free to raise PR. I'll take a look on it

**Comment by Satya758** [comment]
@sinwe Please review the pull request
