### ISSUE TITLE
FindBugs dependency is causing a Black Duck 'High Risk' assessment for the library

### ISSUE THREAD

**Issue by programmatix** [reactor/reactor-scala-extensions#51]
Hi!  We (Couchbase) have been working on getting our SDKs passing the Black Duck OSS security assessment, and hit a stumbling block with your project.

Black Duck has flagged the com.google.code.findbugs:3.0.2 dependency as a 'High Risk'.  It appears to be basing this mainly on it appearing to be unmaintained (it seems to have superseded by SpotBugs).

Now, I'm confused why it's picked up findbugs at all, since I can see you're declaring it with Gradle's implementation scope.  I haven't got to the bottom of that, but I can tell you that Black Duck relies on "mvn dependency:tree" to analyze dependencies for Maven projects, and running this on our project does indeed show findbugs (in runtime Maven scope):

```
> couchbase-jvm-clients/scala-client$ mvn dependency:tree
...
[INFO] +- io.projectreactor:reactor-scala-extensions_2.12:jar:0.5.0:compile
[INFO] |  \- com.google.code.findbugs:jsr305:jar:3.0.2:runtime
...
```
and that it also appears in 
https://repo1.maven.org/maven2/io/projectreactor/reactor-scala-extensions_2.13/0.5.0/reactor-scala-extensions_2.13-0.5.0.pom

This is for project https://github.com/couchbase/couchbase-jvm-clients, btw.

I'm opening this ticket so you're aware of this, and perhaps so we can explore solutions?  It seems like perhaps findbugs could be upgraded to spotbugs, but really, I think the issue is that findbugs should not be appearing in the pom.xml at all?

**Comment by sinwe** [comment]
Thanks for reporting it, @programmatix.
I'll look into it.

**Comment by sinwe** [comment]
Fixed in v0.5.1

**Comment by sinwe** [comment]
@programmatix I've removed findbugs dependencies from the project.
It's release v0.5.1. Please try it.

**Comment by programmatix** [comment]
Thank you for the exceptionally quick work @sinwe, tested 0.5.1 and findbugs is removed as expected - cheers!
