### ISSUE TITLE
Remove Cats Effect

### ISSUE THREAD

**Issue by jpork** [reactor/reactor-scala-extensions#73]
I think cats-effects is a bad and unnecessary dependency for this library. It should be removed. 

For resource management one could use [Flux.using()](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html) or [scala.util.using()](https://www.scala-lang.org/api/current/scala/util/Using$.html).

**Comment by sinwe** [comment]
I agree... I don't think it's worth it to bring the whole cats library just to get bracket.

I'll try to come up with different approach.
