### ISSUE TITLE
Switch to Github Actions for CI

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-scala-extensions#75]
See reactor/reactor#690 for context.

This includes both PR checks and push checks on maintenance branches.
We'll also need to remove `travis.yml` file if travis was used, and do the following repo config changes:
 - [ ] remove travis app integration
 - [ ] remove `.travis.yml`
 - [ ] remove CircleCI integration (`.circleci/`)
 - [ ] change the "required checks" to include the new ci jobs

**Comment by simonbasle** [comment]
@sinwe will you be able to make the switch ?

**Comment by sinwe** [comment]
I think scala extensions already have GHA running in parallel. I'll check it out.

**Comment by simonbasle** [comment]
that would be easy then, this turns into simply removing travis in that case 😉

**Comment by simonbasle** [comment]
oh I just noticed that there is `circleCI` build as well. Adding "remove .travis.yml` and `.circleci/` to the list of tasks. (unless you want to keep circleCI on top of GHA @sinwe ?)

**Comment by sinwe** [comment]
CircleCI is never used, it was just a try. I'll remove it.
